# Generated by Django 4.1.7 on 2023-05-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paras', '0002_databook_date_databook_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databook',
            name='Author',
            field=models.CharField(default='fac', max_length=40),
        ),
        migrations.AddField(
            model_name='databook',
            name='Subject',
            field=models.CharField(default='computer science', max_length=80),
        ),
    ]
