# Generated by Django 4.1.7 on 2023-05-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paras', '0003_databook_author_databook_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='fackey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='stukey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=36, unique=True)),
            ],
        ),
    ]
